// <auto-generated />
namespace Community.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Cityupdate2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cityupdate2));
        
        string IMigrationMetadata.Id
        {
            get { return "202210150520364_City-update2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
